root = "."
tmp_dir = "tmp"

[build]
cmd = "go build -o ./tmp/main ."
full_bin = "MODE=dev tmp/main"
include_ext = ["go", "html", ".json"]
exclude_dir = ["tmp"]
include_dir = []
exclude_file = []
exclude_regex = ["_test.go"]
exclude_unchanged = false
follow_symlink = true
log = "air.log"
delay = 1000 # ms
stop_on_error = true
send_interrupt = false
kill_delay = 500 # ms

[log]
time = true 

[color]
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
clean_on_exit = true
